import { POINT_TYPE } from '@p/EditorTools';

export const ALL_POINTS = [
  POINT_TYPE.LEFT_BOTTOM,
  POINT_TYPE.LEFT_CENTER,
  POINT_TYPE.LEFT_TOP,
  POINT_TYPE.RIGHT_BOTTOM,
  POINT_TYPE.RIGHT_CENTER,
  POINT_TYPE.RIGHT_TOP,
  POINT_TYPE.TOP_CENTER,
  POINT_TYPE.BOTTOM_CENTER,
];

export const TEXT_POINTS = [
  POINT_TYPE.LEFT_BOTTOM,
  POINT_TYPE.LEFT_CENTER,
  POINT_TYPE.LEFT_TOP,
  POINT_TYPE.RIGHT_BOTTOM,
  POINT_TYPE.RIGHT_CENTER,
  POINT_TYPE.RIGHT_TOP,
];
