import { POINT_TYPE } from '../enum/point-type';

/**
 * 所有的锚点
 */
export const ALL_POINT: POINT_TYPE[] = [
  POINT_TYPE.LEFT_TOP,
  POINT_TYPE.TOP_CENTER,
  POINT_TYPE.RIGHT_TOP,
  POINT_TYPE.RIGHT_CENTER,
  POINT_TYPE.RIGHT_BOTTOM,
  POINT_TYPE.BOTTOM_CENTER,
  POINT_TYPE.LEFT_BOTTOM,
  POINT_TYPE.LEFT_CENTER,
];

/**
 * 中心的锚点
 */
export const CENTER_POINT = [
  POINT_TYPE.TOP_CENTER,
  POINT_TYPE.LEFT_CENTER,
  POINT_TYPE.RIGHT_CENTER,
  POINT_TYPE.BOTTOM_CENTER,
];
