export const ShapeList = [
  {
    type: 'shape',
    name: 'round-rect',
    width: 100,
    height: 100,
    fill: 'rgba(0, 0, 0, 1)',
    strokeColor: 'rgba(255, 255, 255, 0)',
    strokeWidth: 0,
    x: 0,
    y: 0,
    rx: 30,
    ry: 30,
    strokeType: 'solid',
    strokeLength: 0,
    strokeSpacing: 0,
    opacity: 1,
    style: {
      borderRadius: '24px',
      background: 'rgb(0,0,0)',
      aspectRatio: 1,
      width: '100%',
    },
  },
  {
    type: 'shape',
    name: 'rect',
    width: 100,
    height: 50,
    fill: 'rgba(0, 0, 0, 1)',
    strokeColor: 'rgba(255, 255, 255, 0)',
    strokeWidth: 0,
    x: 0,
    y: 0,
    rx: 0,
    ry: 0,
    strokeType: 'solid',
    strokeLength: 0,
    strokeSpacing: 0,
    opacity: 1,
    style: {
      aspectRatio: '1 / 0.5',
      background: 'rgb(0,0,0)',
      width: '100%',
    },
  },
];
